name: Secrets Pipeline

on:
  push:
    branches: 
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Environment Variables
        env:
          APP_NAME: "MyDevopsApp"
          APP_VERSION: "2.0"
        run: |
          echo "App Name: $APP_NAME"
          echo "Version: $APP_VERSION"

      - name: Use Github Secrets
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD}}
          API_KEY: ${secrets.API_KEY}}
        run: |
          echo "Password length: ${#DB_PASSWORD"}
          echo "SECRETS LOADED SUCCESSFULLY"
  
