name: Test Pipeline

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/checkout@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install pytest

      - name: Create test file
        run: |
          cat > test_app.py <<'EOF'
          def add(a,b):
            return a + b

          def test_add():
            assert add(2,3) == 5
            assert add(0,0) == 0
            print("All passed")
          EOF
          
      - name: Run tests
        run: pytest test_app.py -v

      - name: Tests passed
        run: echo "All passed -deploy"
